services:
  postgres:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - db-pg-data:/var/lib/postgresql/data

volumes:
  db-pg-data:
